[package]
name = "ip-in-subnet"
version = "0.1.0"
authors = ["perdumonocle <konstantin_1987@mail.ru>"]
edition = "2018"
description = "Checking that subnet contains an IP address"
license = "MIT"

[dependencies]
netaddr2 = "0.7.1"
